name: Deploy React App to Azure Static Web Apps

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev 

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your app requires

      # Step 3: Install dependencies
     
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd my-app 
          npm install

      # Step 4: Inject environment variables
      - name: Set up environment variables
        run: |
          touch ./my-app/.env
          echo "REACT_APP_CLIENT_ID: ${{ vars.REACT_APP_CLIENT_ID }}" >> ./my-app/.env
          echo "REACT_APP_TENANTID: ${{ vars.REACT_APP_TENANTID }}" >> ./my-app/.env
          echo  "REACT_APP_BASEURL: ${{ vars.REACT_APP_BASEURL }}" >> ./my-app/.env
          cat ./my-app/.env

      # Step 5: Build the React app
      - name: Build React app
        run: |
          cd my-app 
          CI=false npm run build

      # Step 6: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/my-app"                # Root directory of your app
          output_location: "build"         # Build output directory
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_OCEAN_0D5FBD900 }}