# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dfpx

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up environment variables
        run: |
          touch ./my-app/.env
          echo "REACT_APP_CLIENT_ID=${{ vars.REACT_APP_CLIENT_ID }}" >> ./my-app/.env
          echo "REACT_APP_TENANTID=${{ vars.REACT_APP_TENANTID }}" >> ./my-app/.env
          echo "REACT_APP_BASEURL=${{ vars.REACT_APP_BASEURL }}" >> ./my-app/.env
          cat ./my-app/.env

      - name: npm install, build, and test
        run: |
          cd my-app
          CI=false
          npm install
          npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'dfpx'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F5A3A324CFD24C738DBABA6B5841256C }}
            package: ./my-app/build
      